// <auto-generated />
using System;
using APBD_cw8_s29640.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBD_cw8_s29640.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260616231109_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBD_cw8_s29640.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Stanisław",
                            LastName = "Lem"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Olga",
                            LastName = "Tokarczuk"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Andrzej",
                            LastName = "Sapkowski"
                        });
                });

            modelBuilder.Entity("APBD_cw8_s29640.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.ToTable("Books", null, t =>
                        {
                            t.HasCheckConstraint("CK_Books_PublishedYear", "[PublishedYear] > 1900");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Isbn = "9788374802550",
                            PublishedYear = 1961,
                            Title = "Solaris"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Isbn = "9788374802567",
                            PublishedYear = 1964,
                            Title = "Bajki robotów"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Isbn = "9788308066980",
                            PublishedYear = 2009,
                            Title = "Prowadź swój pług przez kości umarłych"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            Isbn = "9788375780635",
                            PublishedYear = 1993,
                            Title = "Ostatnie życzenie"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            Isbn = "9788375780642",
                            PublishedYear = 1992,
                            Title = "Miecz przeznaczenia"
                        });
                });

            modelBuilder.Entity("APBD_cw8_s29640.Models.Borrowing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Borrowings", (string)null);
                });

            modelBuilder.Entity("APBD_cw8_s29640.Models.Book", b =>
                {
                    b.HasOne("APBD_cw8_s29640.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("APBD_cw8_s29640.Models.Borrowing", b =>
                {
                    b.HasOne("APBD_cw8_s29640.Models.Book", "Book")
                        .WithMany("Borrowings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("APBD_cw8_s29640.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("APBD_cw8_s29640.Models.Book", b =>
                {
                    b.Navigation("Borrowings");
                });
#pragma warning restore 612, 618
        }
    }
}
